### ISSUE TITLE
ホールド機能 + フィールド上のnext, hold表記

### ISSUE THREAD

**Issue by tkuramot** [recursion-blue-team/tetris#41]
### 概要
ホールド機能の実装

**Comment by K4-R4** [comment]
![Screenshot_611](https://user-images.githubusercontent.com/106866329/215083954-1275d4e9-6e7b-4ad5-90eb-b74f4644adce.png)

画像のようにボタンが押されている状態のときにキーボードのスペースを押すと、ボタンとキーボードの両方の入力を受けるようでホールドしてもすぐにホールド前のテトロミノに戻ってしまいます。
ただ、キーボードとボタンを併用しない限り問題はなく、pcの方ではボタンは表示しないと思うので対処していません。
